.TH ANDUTTEYEADM 28 "AUG 2008" Linux "User Manuals"
.SH NAME
andutteyeadm \- Andutteye Management Core CLI
.SH SYNOPSIS
.B andutteyeadm
.B ...
.SH DESCRIPTION
.B andutteyeadm
is the main Andutteye management cli and administration program to load, modify and extract data and information to and from the Andutteye database.
.SH OPTIONS
.IP config
andutteyeadm is using the db settings specified in andutteyedsrv.conf

.SH FILES
.I /etc/andutteyedsrv.conf
.RS
The andutteye server configuration file.
.RE
.SH DIAGNOSTICS
on standard output
 
.RE
.SH BUGS
Report found bugs or suggestions at <www dot andutteye dot com>
.RE
.SH AUTHOR
Andreas Utterberg (andutt) <info at thunderas dot se>
.SH "SEE ALSO"
.BR andutteyedagt (1),
.BR andutteyepst (1),
.BR andutteyedsrv (1)
