.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ANDUTTEYEDAGT 30 "AUG 2008" Linux "User Manuals"
.SH NAME
andutteyedagt \- andutteye agent
.SH SYNOPSIS
.B andutteyed
.B ...
.SH DESCRIPTION
.B andutteyed
is the andutteye agent. Anduteyed is gathering
runtime statistics and monitor the system based on the configuration file.
Andutteyedagt can be executed in enterprise mode which means that the agent
reports to a andutteye server or in standalone mode. In standalone mode
andutteyedagt will monitor the system and execute recovery actions but will
not try to communicate on the network.
.SH OPTIONS

.SH FILES
.I /opt/andutteye/etc/andutteyedagt.conf
.RS
The andutteye clients configuration file.
.RE
.I /etc/init.d/andutteye
.RS
The andutteye start and stop program.
.SH BUGS
Report found bugs or suggestions at <www dot andutteye dot com>
.SH AUTHOR
Andreas Utterberg (andutt) <info at thundera dot se>
.SH "SEE ALSO"
.BR andutteyedsrv (1),
.BR andutteyeadm (1),
